language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.0
    - android-29

script:
  - touch local.properties
  - gradle clean build test
