name: itf-chartizate-android

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Set up Android 30
      uses: jesperancinhaorg/android-action@v0.0.1

    - name: Creates properties
      run: touch local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Creates properties
      run: touch local.properties

    - name: Download Android dependencies
      run: ./gradlew androidDependencies

    - name: Create reports
      run: 	gradle wrapper --gradle-version 7.3.3 &&
            ./gradlew clean build test jacocoTestReport -i &&
           	java -jar libs/jacococli.jar report itf-chartizate-android/build/jacoco/testReleaseUnitTest.exec --classfiles itf-chartizate-android/build/.transforms/*/transformed/out/jars/classes.jar --xml itf-chartizate-android/build/jacoco/jacocoRelease.xml

    - name: Send Reports
      run: gradle -i
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
